export const SET_ID = 'SET_ID';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_ERROR_SIGNIN = 'SET_ERROR_SIGNIN';
export const SET_ERROR_SIGNUP = 'SET_ERROR_SIGNUP';
export const SET_SUCCESS_SIGNUP = 'SET_SUCCESS_SIGNUP';
export const SET_EYE_ICON_VISIBLE = 'SET_EYE_ICON_VISIBLE';
export const SET_IS_SIGNIN_ACTIVE = 'SET_IS_SIGNIN_ACTIVE';
